# Introduction

This is my project to learn intuition behind ML algorithms. First, I started with Linear Regression. Both Gradient Descent and Cost Function are my solutions to Andrew NG Coursera Machine Learning Course Assignments. This and following project (that I will be working on) will be a study notebooks for myself, in order to remember how the algorithms work. 

Let's go with Linear Regression.


# Linear Regression

Linear regression (hence will be written as LR) is an modelling approach to determine the relationship between a dependent variable (y) and one or many independent variables (X).If the lenght of X equals to 1, we call this Simple or Univariate LR. If X has more variables, the process is called multiple LR.  

Before going deep into LR functions, we need to know assumptions of LR. Regression has 5 assumptions:

1. Linear Relation : The relationship between dependent and independent variable must be linear. 
2. Multivariate Normality: LR also requires all variables to be normally distributed. For normal distribution check Q-Q plots, histograms, Kolomogrov-Smirnov test, skewness and kurtosis values. 
3. No Multicollinearity : LR requires independent variables not correlated with each other. To determine multicollinearity, Variance Inflation Factor value, correlation matrix (sns.heatmap(df.corr()) or tolerance.  If multicollinearity present in the data, we should try removing one of the variables or create a new feature.
    - the tolerance measures the influence of one independent variable on all other independent variables; the tolerance is calculated with an initial linear regression analysis.  Tolerance is defined as T = 1 – R² for these first step regression analysis.  With T < 0.1 there might be multicollinearity in the data and with T < 0.01 there certainly is.
    - the variance inflation factor of the linear regression is defined as VIF = 1/T. With VIF > 5 there is an indication that multicollinearity may be present; with VIF > 10 there is certainly multicollinearity among the variables.
    
4. No autocorrelation : Autocorrelation occurs when the residuals are not independent from each other.  In other words when the value of y(x+1) is not independent from the value of y(x).  If autocorrelation present, we might not be sure which variable estimates the dependent variable better than each other. Durbin-Watson d score is used to determine autocorrelation of the data. d scores around 2 is accepted as no autocorrelation. 1.5<d<2.5 (ranging 0 to 4) is assumed that data has autocorrelation.

5. Homoscedasticity : LR requires residuals near the regression line. The best way to evaluate that sns.regplot or scatter plots.




### LR Hypothesis

$$ h_\theta(x) = \theta_0 + \theta_1x_1 $$

Where;

* $h_\theta(x)$ is the hypothesis 

* x  is the independent variable

* $ \theta $ is the model’s parameter vector, containing the bias term $ \theta_0 $ and the feature weights $ \theta_1 $ to $ \theta_n$.

### Performance Measures

To determine how well or poorly LR model trained we need to calculate an error value. For LR we have Mean Squared Error, Root Mean Squared Error. To calculate MSE of given X is :

$$ MSE(X, h_{\theta}) = \frac{1}{m}\sum_{i=1}^m(\theta^Tx^i-y^i)^2 $$


#### Normal Equation

To find the $\theta$ value that minimize cost function, we use normal equation formula:

$$ \hat{\theta} = (X^TX)^{-1}X^Ty$$
                     
                                         





### Cost Function and Gradient Descent

Cost Function (aka Loss , Error Function) is a function that maps an event or values of one or more variables onto a real number intuitively representing some "cost" associated with the event. An optimization problem seeks to minimize a loss function. Gradient Descent algorithm is used for optimizing cost function. 

The common example for GD is climbing down a foggy mountain. You can only feel the slope, but cannot see where you are going. The easiest way to go down, take the steepest slope. That what GD does for LR.

First, take a random 𝜃 value (random initialization), improve it slowly (learning_rate) to find global (or local) minima. Learning rate is how big or small your step is. A big learning rate may cause you to skip minimum, or a small learning rate might take too much time.

Gradient Descent Formula:

$$ \frac{dJ}{dw} = \frac{1}{m}\sum_{i=1}^m(\theta^Tx^{(i)}-y^{(i)})x_j^{i} $$

Update Functions (since GD is an iterative function) :

$$ w = w - \alpha * dw $$

$$ b = b - \alpha * db $$ 


Mathematical Formulas :

$$ \frac{dJ}{dw} = dw = \frac{1}{N} \sum_{i=1}^n2x_i(\hat y - y_i) $$
                     
$$ \frac{dJ}{db} = db = \frac{1}{N} \sum_{i=1}^n2(\hat y - y_i) $$

#### Batch Gradient Descent

In Batch Gradient Descent, all the training data is taken into consideration to take a single step. We take the average of the gradients of all the training examples and then use that mean gradient to update our parameters. Batch Gradient Descent is great for convex or relatively smooth error manifolds. In this case, we move somewhat directly towards an optimum solution.

Partial Derivatives for Cost Function: 
$$\frac{\partial}{\partial\theta_j}MSE(\theta) = \frac{2}{m}\sum_{i=1}^m(\theta^Tx^{(i)}-y^{(i)})x_j^{i}$$


Gradinet Vector of the Cost Function: 
$$ = \frac{2}{m} X^T(X\theta-y) $$


#### Stochastic Gradient Descent

The main problem for Batch Gradient Descent is that it uses all the data for determining global minima. However this is problematic for large datasets cause of the computation durations. 

On the other hand Stochastic Gradient Descent picks random instance from the data and computes the gradient based on only one instance. This makes the S-GD way more faster and ram efficient (only used instance is saved to ram).

S-GD due its stochastic (random) nature, is less regular than Batch GD. S-GD moves up and down and gently moves down to global minima ( at least nearly). However, it never stops and tries to move around a bit more. Overall, it will end up close to minimum but not exactly. 
But this specification has one positive outcome. When to cost function is irregular and has local minima's, S-GD is more likely to find Global Minima, and it is considered better than Batch Gradient Descent. 

As mentioned above, randomness is good to escape local optima, however it is bad that it can never settle at the minimum. To avoid that, we need to decrease the learning rate gradually. First start with a big learning rate to jump out of the starting point and local minima, than gradually decrease the learnin rate to allow the algorithm settle at the global minima. 



In [184]:
import numpy as np

def normal_equation(X,y):
    """ Calculates normal equation for linear regression. 
    Normal equation finds the value that minimizes theta.
    theta[0] is intercept, theta[1] is coef_
    """
    X_lr = np.concatenate((np.ones((len(X),1)),X),axis=1)
    global theta
    theta = np.linalg.pinv(X_lr.T.dot(X_lr)).dot(X_lr.T).dot(y)
    return theta

Scikit_learn LR uses scipy.linalg.lstsq() function. and it uses pseudoinverse of matrix $X^+$. Let's see how O'reilly book defines this situation:

- The pseudoinverse itself is computed using a standard matrix factorization technique called Singular Value Decomposition (SVD) that can decompose the training set matrix X into the matrix multiplication of three matrices U Σ VT (see numpy.linalg.svd()). The pseudoinverse is computed as X+ = VΣ+UT. To compute the matrix Σ+, the algorithm takes Σ and sets to zero all values smaller than a tiny threshold value, then it replaces all the non-zero values with their inverse, and finally it transposes the resulting matrix. This approach is more efficient than computing the Normal Equation, plus it handles edge cases nicely: indeed, the Normal Equation may not work if the matrix XTX is not invertible (i.e., singular), such as if m < n or if some features are redundant, but the pseudoinverse is always defined.

In [185]:
def prediction(X, theta):
    """Predicts y with given X,
    do not forget to calculate theta with normal_equation
    """
    x_new = np.concatenate((np.ones((len(X),1)),X),axis=1) #add ones (x0) to X
    y_pred = x_new.dot(theta)
    return y_pred

In [186]:
def mse(y_pred,y):
    """
    Calculates mean squared error
    """
    m = y_pred.shape
    mse = pow(np.sum(y- y_pred),2)/m
    return mse

def rmse(mse):
    """
    Calculates Root mean squared error
    """
    return np.sqrt(mse)

In [187]:
# Cost Function ; this code is a part of Andrew NG's coursera assignments

def cost_function(X,y,theta):
    """ Computes Cost Function for linear regression. 
    Computes the loss function using theta parameters
    for linear regression to fit data points X and y.    
    """
    J = 0 # this is the cost function, at the end, code will return this
    
    m = y.shape[0] 
    
    X = np.concatenate((np.ones((len(X),1)),X),axis=1) #add ones (x0) to X
    
    J = np.sum((np.dot(X, theta) - y)**2)/(2*m)
    
    return J
    

In [188]:
# Gradient Descent, this one also a part of Andrew NG's coursera assignment

def GradientDescent(X, y, theta, alpha, num_iters):
    """
    Performs gradient descent to learn `theta`. Updates theta by taking `num_iters`
    gradient steps with learning rate `alpha`.
    """
    # Initialize some useful values
    m = y.shape[0]  # number of training examples
    
    # make a copy of theta, to avoid changing the original array, since numpy arrays
    # are passed by reference to functions
    theta = theta.copy()
    
    X = np.concatenate((np.ones((len(X),1)),X),axis=1) #add ones (x0) to X
    
    for i in range(num_iters):
        
        gredients = (1/m) * X.T.dot(X.dot(theta) - y)
        
        theta = theta - alpha * gredients
    
    return theta

In [189]:
def batch_gradient(X,y, theta, learning_rate = 0.01, num_iters = 1000):
    m = y.shape[0]
    
    X = np.concatenate((np.ones((len(X),1)),X),axis=1) #add ones (x0) to X
    
    J_history = []
    
    for i in range(num_iters):
        
        gradients = (2/m) * X.T.dot(X.dot(theta) - y)
        
        theta -= learning_rate * gradients
        
        J_history.append(gradients)
    
    return theta

In [190]:
# Testing
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [191]:
theta = normal_equation(X,y)
theta

array([[3.7528377 ],
       [3.12961683]])

In [192]:
y_pred = prediction(np.array([[2],[1]]), theta)

In [193]:
cost_function(X,y,theta)

0.638378355975523

In [194]:
GradientDescent(X, y, theta=theta, alpha= 0.1, num_iters=100)

array([[3.7528377 ],
       [3.12961683]])

In [195]:
batch_gradient(X, y, theta=theta)

array([[3.7528377 ],
       [3.12961683]])